export const LOGO_ASCII = {
    "width": 25,
    "height": 21,
    "chars": [
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        ":",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        "-",
        "-",
        ":",
        ":",
        ":",
        " ",
        " ",
        " ",
        ":",
        ":",
        ":",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        " ",
        " ",
        " ",
        " ",
        " ",
        "-",
        "-",
        "-",
        ":",
        ":",
        ":",
        ":",
        ":",
        ":",
        ":",
        ":",
        ":",
        ":",
        ":",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        " ",
        " ",
        " ",
        "-",
        "-",
        "-",
        "-",
        ":",
        ":",
        ":",
        ":",
        ":",
        ":",
        ":",
        ":",
        ":",
        ":",
        ":",
        ":",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        "-",
        " ",
        "-",
        "-",
        "-",
        "-",
        ":",
        ":",
        ":",
        ":",
        ":",
        ":",
        ":",
        ":",
        ":",
        ":",
        ":",
        ":",
        ":",
        ":",
        "-",
        " ",
        " ",
        " ",
        " ",
        " ",
        "-",
        "-",
        "-",
        "-",
        ":",
        ":",
        ":",
        ":",
        ":",
        " ",
        " ",
        ":",
        ":",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        ":",
        ":",
        ".",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        ".",
        ".",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        ".",
        ".",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        ":",
        ".",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        ":",
        ":",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        ":",
        ":",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        ":",
        ":",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        ":",
        ":",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        ":",
        ":",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        ":",
        ":",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        "-",
        "-",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        "-",
        "-",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        "-",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        "-",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        "-",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " "
    ],
    "colors": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "rgb(0,221,0)",
        "rgb(3,230,3)",
        "rgb(2,233,2)",
        "rgb(4,241,4)",
        "rgb(4,247,4)",
        "rgb(4,249,4)",
        "rgb(2,248,2)",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "rgb(4,234,4)",
        "rgb(5,225,5)",
        "rgb(4,218,4)",
        "rgb(4,216,4)",
        "rgb(3,208,3)",
        null,
        null,
        null,
        "rgb(2,204,2)",
        "rgb(3,216,3)",
        "rgb(4,221,4)",
        "rgb(4,227,4)",
        "rgb(4,234,4)",
        "rgb(5,241,5)",
        "rgb(5,249,5)",
        "rgb(5,255,5)",
        "rgb(4,253,4)",
        "rgb(5,243,5)",
        null,
        null,
        null,
        null,
        null,
        "rgb(4,241,4)",
        "rgb(4,238,4)",
        "rgb(4,231,4)",
        "rgb(3,223,3)",
        "rgb(4,217,4)",
        "rgb(3,210,3)",
        "rgb(3,204,3)",
        "rgb(2,199,2)",
        "rgb(3,194,3)",
        "rgb(3,194,3)",
        "rgb(3,203,3)",
        "rgb(3,206,3)",
        "rgb(4,212,4)",
        "rgb(3,217,3)",
        "rgb(4,226,4)",
        "rgb(4,233,4)",
        "rgb(5,242,5)",
        "rgb(5,251,5)",
        "rgb(5,255,5)",
        "rgb(5,255,5)",
        "rgb(3,250,3)",
        null,
        null,
        null,
        "rgb(5,250,5)",
        "rgb(4,243,4)",
        "rgb(4,234,4)",
        "rgb(4,224,4)",
        "rgb(3,216,3)",
        "rgb(3,207,3)",
        "rgb(3,201,3)",
        "rgb(2,195,2)",
        "rgb(2,191,2)",
        "rgb(2,188,2)",
        "rgb(2,189,2)",
        "rgb(2,191,2)",
        "rgb(3,196,3)",
        "rgb(3,202,3)",
        "rgb(3,209,3)",
        "rgb(3,217,3)",
        "rgb(4,226,4)",
        "rgb(4,235,4)",
        "rgb(4,243,4)",
        "rgb(5,250,5)",
        "rgb(5,249,5)",
        "rgb(2,249,2)",
        "rgb(0,241,0)",
        null,
        "rgb(4,253,4)",
        "rgb(4,248,4)",
        "rgb(5,239,5)",
        "rgb(3,227,3)",
        "rgb(4,218,4)",
        "rgb(3,208,3)",
        "rgb(3,200,3)",
        "rgb(2,191,2)",
        "rgb(2,182,2)",
        "rgb(3,173,3)",
        "rgb(2,172,2)",
        "rgb(1,175,1)",
        "rgb(2,174,2)",
        "rgb(1,183,1)",
        "rgb(3,192,3)",
        "rgb(2,199,2)",
        "rgb(3,208,3)",
        "rgb(3,216,3)",
        "rgb(5,220,5)",
        null,
        null,
        null,
        null,
        null,
        "rgb(2,249,2)",
        "rgb(5,253,5)",
        "rgb(5,240,5)",
        "rgb(4,230,4)",
        "rgb(4,220,4)",
        "rgb(3,210,3)",
        "rgb(3,200,3)",
        "rgb(3,190,3)",
        "rgb(3,173,3)",
        null,
        null,
        "rgb(1,162,1)",
        "rgb(2,162,2)",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "rgb(0,153,0)",
        "rgb(1,154,1)",
        "rgb(0,149,0)",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "rgb(0,148,0)",
        "rgb(0,142,0)",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "rgb(0,148,0)",
        "rgb(1,137,1)",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "rgb(1,154,1)",
        "rgb(0,148,0)",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "rgb(1,164,1)",
        "rgb(2,158,2)",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "rgb(2,174,2)",
        "rgb(2,168,2)",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "rgb(2,183,2)",
        "rgb(2,179,2)",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "rgb(2,195,2)",
        "rgb(2,190,2)",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "rgb(3,204,3)",
        "rgb(4,201,4)",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "rgb(3,214,3)",
        "rgb(4,213,4)",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "rgb(4,222,4)",
        "rgb(5,223,5)",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "rgb(4,232,4)",
        "rgb(4,233,4)",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "rgb(5,246,5)",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "rgb(0,244,0)",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "rgb(0,237,0)",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    ]
} as const
